### ISSUE TITLE
demo中部分类包名不对

### ISSUE THREAD

**Issue by liuyu1992** [wechat-group/weixin-mp-demo-springboot#1]
import me.chanjar.weixin.mp.bean.message.WxMpXmlMessage;
import me.chanjar.weixin.mp.bean.message.WxMpXmlOutImageMessage;
import me.chanjar.weixin.mp.bean.message.WxMpXmlOutMessage;
这三个类做了重构之后麻烦更新到demo去~

**Comment by binarywang** [comment]
请问你是在哪个类里看到的问题，这个项目我实际跑过，没问题，也没有编译错误

**Comment by binarywang** [comment]
我知道怎么回事了，我上午提交过最新的修改了，你是在这之前访问的项目，所以会有问题，现在再试试吧！
