### ISSUE TITLE
miss dependency in pom

### ISSUE THREAD

**Issue by ysjiang4869** [wechat-group/weixin-mp-demo-springboot#2]
I think you missed   following dependency in pom.xml in order to support @ConfigurationProperties
`   <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>`

**Comment by ysjiang4869** [comment]
嗯， 实际配置到intellji的时候，运行是可以通过的，但是没有这个依赖会让properties这个bean不能注入，application.properties文件也不能识别，按照spring-boot的文档这个依赖是需要手动添加的~

**Comment by binarywang** [comment]
我还是没太明白，你说不能注入？是说运行时候抱错了吗？我这边运行起来可以跟微信正常交互操作，另外如果有QQ，请入群讨论吧，能快速有效些

**Comment by ysjiang4869** [comment]
我试了一下，可以的，不添加依赖也能够正常交互，但是application.properties文件中会提示can't resolve configuration propertity ,对于运行没有影响的

**Comment by binarywang** [comment]
你说的提示信息是在哪儿看到的？能否发下日志，我这里并没有看到，而且我调试看了下，那些属性都是可以正常注入的。

**Comment by ysjiang4869** [comment]
是可以正常注入的，这点我之前搞错了，这个不是报错，不影响程序运行的（好像这边不能发截图）只是在properties文件中输入wechat不能自动补全输入完成后会提示不能解析，对程序运行本身没有影响，方便给个群号码吗？我可以发图片给你

**Comment by binarywang** [comment]
QQ群在这里有说明 https://github.com/wechat-group/weixin-java-tools
